### ISSUE TITLE
The faasm/toolchain expects a compiler at /usr/local/code/faasm/toolchain/install/bin/clang++

### ISSUE THREAD

**Issue by bushidocodes** [lsds/Faasm#100]
After running `./bin/toolchain.sh`, and then executing the example from the README, the client errors because clang is not where it expects.

```
(faasm) root@docker-desktop:/usr/local/code/faasm# cd func/
(faasm) root@docker-desktop:/usr/local/code/faasm/func# ls
CMakeLists.txt  demo  dynlink  errors  knative_native.py  onnx  polybench  python  run_knative_native.sh  sgd  tf
(faasm) root@docker-desktop:/usr/local/code/faasm/func# cd demo
(faasm) root@docker-desktop:/usr/local/code/faasm/func/demo# inv compile --func=demo/hello
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
System is unknown to cmake, create:
Platform/Wasm to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake    Your CMakeCache.txt file was copied to CopyOfCMakeCache.txt. Please send that file to cmake@www.cmake.org.
CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_C_COMPILER:

    /usr/local/code/faasm/toolchain/install/bin/clang

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_CXX_COMPILER:

    /usr/local/code/faasm/toolchain/install/bin/clang++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
```

**Comment by bushidocodes** [comment]
I symlinked clang and clang++ at the locations indicated above, and it got me a bit further.  I assume there might be something else I need to symlink? 

```
[100%] Linking CXX executable hello.wasm
cd /usr/local/code/faasm/build/func/demo && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/hello.dir/link.txt --verbose=1
/usr/local/code/faasm/toolchain/install/bin/clang++ --target=wasm32 --sysroot=/usr/local/faasm/llvm-sysroot   -O3 -msimd128 --sysroot=/usr/local/faasm/llvm-sysroot          -Xlinker --no-entry         -Xlinker --export=main         -Xlinker --export=_faasm_zygote         -Xlinker --max-memory=1073741824         -Xlinker --stack-first         -Xlinker --threads         -Xlinker --no-check-features         -Wl,-z,stack-size=4194304 -Wl,      CMakeFiles/hello.dir/hello.cpp.obj  -o hello.wasm -lfaasm -ldlmalloc
wasm-ld: error: unknown argument: --no-check-features
wasm-ld: error: cannot open /usr/lib/llvm-8/lib/clang/8.0.1/lib/libclang_rt.builtins-wasm32.a: No such file or directory
clang: error: lld command failed with exit code 1 (use -v to see invocation)
```

**Comment by Shillaker** [comment]
Let me have a look now, this should work out of the box.

Out of interest what sort of system are you running on?

**Comment by bushidocodes** [comment]
Yeah, my toolchain is pretty complicated. Currently using the Windows Subsystem for Linux 2 + Ubuntu 18 LTS + Docker for Windows (using a WSL backend).  It's the mullet of systems: Business in the front, Party in the back. 

In theory, everything should be behaving as with a native Ubuntu system. I'm happy to retry on a native Ubuntu partition if you think that might be relevant here. I just couldn't identify the mechanism that was responsible for putting the relevant tools in `/usr/local/code/faasm/toolchain/install/bin/`, so I wasn't sure if it would make a difference.

I did notice that you have `toolchain/install` in `toolchain/.gitignore`, so I suppose a good way to test on your system might be to move `toolchain/install` to `toolchain/install2` and then run through your documented process to see if `install` gets regenerated.

Thanks for the help!

**Comment by Shillaker** [comment]
:laughing: at the mullet. As much as it's non-standard you're right, it ought to work properly and the problem was with the code. I'd neglected the README for a while but the PR mentioned above should fix both issues you raised. 

With `docker pull faasm/worker`, `docker pull faasm/upload` and `docker pull faasm/toolchain` things should work more smoothly.

Let me know if that works and thanks again for raising this.

**Comment by bushidocodes** [comment]
All the `docker-compose` stuff now worked well for me! Thank you for the fix. I think you can feel free to close this one.
