### ISSUE TITLE
`set_up_benchmarks` triggers error around AWSSDK

### ISSUE THREAD

**Issue by bushidocodes** [lsds/Faasm#106]
I've run the Ansible setup scripts on a native Ubuntu box, but after restarting, when I try to run ` ./bin/set_up_benchmarks.sh`, I'm getting errors about the AWSSDK library. My goal is basically just to profile faasm locally rather than on cloud providers, so if you can clarify the commands or environment variables I need to set, that should be sufficient.

```sh
/usr/local/code/faasm master*
❯ ./bin/set_up_benchmarks.sh
/usr/local/code/faasm/bench /usr/local/code/faasm
-- Found LLVM 9.0.1
CMake Warning at CMakeLists.txt:79 (find_package):
  By not providing "Findaws-lambda-runtime.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "aws-lambda-runtime", but CMake did not find one.

  Could not find a package configuration file provided by
  "aws-lambda-runtime" with any of the following names:

    aws-lambda-runtimeConfig.cmake
    aws-lambda-runtime-config.cmake

  Add the installation prefix of "aws-lambda-runtime" to CMAKE_PREFIX_PATH or
  set "aws-lambda-runtime_DIR" to a directory containing one of the above
  files.  If "aws-lambda-runtime" provides a separate development package or
  SDK, be sure it has been installed.


CMake Error at CMakeLists.txt:82 (find_package):
  By not providing "FindAWSSDK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "AWSSDK", but
  CMake did not find one.

  Could not find a package configuration file provided by "AWSSDK" with any
  of the following names:

    AWSSDKConfig.cmake
    awssdk-config.cmake

  Add the installation prefix of "AWSSDK" to CMAKE_PREFIX_PATH or set
  "AWSSDK_DIR" to a directory containing one of the above files.  If "AWSSDK"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/usr/local/code/faasm/bench/CMakeFiles/CMakeOutput.log".
```

**Comment by Shillaker** [comment]
Ah yes, there is a switch to turn off the AWS support but it was "on" by default and missed a couple of things. The PR above should have fixed it and it's now off by default too. Thanks again for the interest and for persevering! As always let me know if there are any more issues.

**Comment by bushidocodes** [comment]
I'm not sure if I didn't notice it properly before or if something has changed (probably the former), but the setup playbook is not running to completion. I can't accurately validate this fix until those issues are resolved.

Thank you for your help with this! I appreciate the responsiveness! 👏

**Comment by bushidocodes** [comment]
Ok, I was able to figure out a workaround, and this didn't hang on the AWS SDK any longer. This can probably be closed.

**Comment by Shillaker** [comment]
Ok great! Which setup playbook do you mean? The AWS one? I'll have a look and fix it. 

Cheers

**Comment by Shillaker** [comment]
Ah just seen all the other issues, thanks for the detail! I'll dig into them.
