### ISSUE TITLE
Role llvm not defined

### ISSUE THREAD

**Issue by bushidocodes** [lsds/Faasm#112]
When I run `./bin/set_up_benchmarks.sh`, I get an error about the llvm role.

I was able to get this to work by changing `llvm` to `llvm9`. Considering that you have both `llvm8` and `llvm9`, I'm assuming that there's some sort of implicit branching logic.

**Comment by Shillaker** [comment]
Fixing as part of #117 

Should be using `llvm9` everywhere but I hadn't completed the update
