### ISSUE TITLE
Instructions for installation on localhost

### ISSUE THREAD

**Issue by bushidocodes** [lsds/Faasm#113]
I ran the Ansible playbook locally in a VM. To do this, I did the following:

1. I cloned your git repo in `/usr/local/code`. Given that your repo is named `Faasm`, this yielded `/usr/local/code/Faasm` (notice the capital F)
2. I then changed `provision_bench_host.sh` to have the following line:

```
ansible-playbook --connection=local -i inventory/benchmark.yml benchmark.yml
```

3. I then ran `/usr/local/code/Faasm/bin/provision_bench_host.sh`. The generated a distinct directory `usr/local/code/faasm`. 

I'm an Ansible novice, and I understand that this tool is typically used for remote systems, but I wonder if it might be useful to support a local installation as above. Just wanted to mention this workflow in case it generates any workflow improvement ideas.

**Comment by Shillaker** [comment]
You're right, the `provision_bench_host.sh` script is meant for remote hosts and will, among other localhost-unfriendly things, check out the code (hence the new directory created at `/usr/local/code/faasm`). 

The instructions for local development can be found at [`local_dev.md`](https://github.com/lsds/Faasm/blob/master/docs/local_dev.md), which describes a localhost-friendly Ansible playbook.

I'm tidying this up as part of #117 which I'll merge soon, at which point it should be in a better state.

Cheers!
