### ISSUE TITLE
Permission error creating `/usr/local/faasm/` when running `set_up_benchmarks.sh`

### ISSUE THREAD

**Issue by bushidocodes** [lsds/Faasm#118]
I'm not sure if this is supposed to be `/usr/local/code/faasm/object/demo`, but I used sudo to mkdir and chown `/usr/local/faasm` to get past this.

```
[2019-12-03 12:35:13.429] [console] [info] Generating machine code for demo/noop
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::create_directories: Permission denied: "/usr/local/faasm/object/demo"
./bin/set_up_benchmarks.sh: line 30:  7098 Aborted                 (core dumped) ./bin/codegen_func demo noop
```

**Comment by Shillaker** [comment]
This should now be created as part of the local and benchmark machine set-ups (https://github.com/lsds/Faasm/blob/master/ansible/roles/runtime_fs/tasks/main.yml). 

As long as the directory is there and is suitably permissive things should work ok. As you say:

```bash
sudo mkdir -p /usr/local/faasm
sudo chown -R $USER:$USER !$
```
