### ISSUE TITLE
When running memory benchmarks as root, errors due to missing binaries

### ISSUE THREAD

**Issue by bushidocodes** [lsds/Faasm#119]
Setting up the benchmarks seems to have placed a bunch of things in `~/faasm/`, but when following the benchmark instructions, you suggest running as root, and this errors out because the expected binaries aren't in `/root/faasm/bench`.

To get past this, I just copied `~/faasm/bench` to `/root/faasm/bench`

**Comment by Shillaker** [comment]
Ah yes good point, I wonder if a symlink might be better, I'll update the docs.
