### ISSUE TITLE
Polybench Instructions Clarification (inv upload-all)

### ISSUE THREAD

**Issue by bushidocodes** [lsds/Faasm#121]
The instructions include the following:

```
# Upload (must have an upload server running)
inv upload-all
```

Does this mean that we need to start an upload server running before this command? If so, how?

This is what I see running this:

```
/usr/local/code/faasm/toolchain master
❯ inv upload-all
Creating config file at /home/sean/faasm/faasm.ini
```

**Comment by Shillaker** [comment]
Yes, that's the `upload` target that will run the upload server on port `8002`. It should have been built at some point beforehand. I'll add it to the `set_up_benchmarks.sh` script so if you rerun that you should find the binary wherever those are built (`~/faasm/bench/bin/upload`).
