### ISSUE TITLE
Sharing state in python

### ISSUE THREAD

**Issue by nayakajay** [lsds/Faasm#212]
I was trying to understand how to share data between a created thread and main func
I am trying to follow and reuse code from these 2 examples present in func/python:
1. func/python/state_test_read.py ==> for sharing data without passing information
2. func/python/chain.py                 ==> to create threads and wait for it

Here is the snippet I am using
```
from pyfaasm.core import chainThisWithInput, awaitCall, setState, getState, \
    pullState, pushState, getFunctionIdx, getInput
import json

sharedStateSize=1024
inKey='in-key'

def dict_to_bytes(the_dict):
    return json.dumps(the_dict).encode('utf-8')

def bytes_to_dict(the_bytes):
    return json.loads(the_bytes.decode('utf-8'))

def inputHandle(i_data):
    pullState(inKey, sharedStateSize)
    response = getState(inKey, sharedStateSize)
    response = bytes_to_dict(response)
    response['num'] = 25
    setState(inKey, dict_to_bytes(response))
    pushState(inKey)

def init():
    return {'num': 0.0}

def main_func():
    idx = getFunctionIdx()
    print("Got function index {}".format(idx))

    if idx == 0:
        print("Main chaining entry point")
        call_a = chainThisWithInput(1, b'00')

        setState(inKey, dict_to_bytes(init()))
        pushState(inKey)
        res_a = awaitCall(call_a)
        print("Res Code: {}".format(res_a))
        inResponse = getState(inKey, sharedStateSize)
        print(bytes_to_dict(response))

    elif idx == 1:
        inputHandle(getInput())

if __name__ == "__main__":
    main_func()
```

json.decoder.JSONDecodeError: Extra data: line 1 column 67 (char 66)
in both the main_func as well as the inputHandle () where I invoke
bytes_to_dict after I get state.
![Error_4_decode](https://user-images.githubusercontent.com/35248326/79062071-70675880-7cb4-11ea-9933-258d5cff3c6e.png)

When I change the value of ```sharedStateSize``` to 512 I get:
I see a SIGSEGV
![Error_3_dict](https://user-images.githubusercontent.com/35248326/79062054-42821400-7cb4-11ea-97d1-c3298bc1d9dc.png)

There are few things I want to accomplish
1. Share a dict with the created thread (I am assuming awaitCall creates a thread and executes it)
2. Update that dict in the created thread
3. Use that dict in main, and possibly pass it around to more threads.

I am not sure if I understand the APIs pretty well, but the restriction I am putting here is
the dict present in "init" may have more key:value pairs, but I won't add more key:value pairs in the thread. I will only update them.

Please let me know if this is the way or is there a better way.

**Comment by Shillaker** [comment]
Hey @nayakajay thanks for raising this. Sharing a dictionary through state should be fine in the way you describe, I'll have a go myself later and add a worked example to the docs. I'll also update the listing mentioned in #213 ; I think that bit's just out of date.

Thanks again!

**Comment by nayakajay** [comment]
Thanks, as of now, I still see those errors. I will refactor my snippet once you add a worked out example.

**Comment by Shillaker** [comment]
Just FYI I'm currently working on this. Some of the Python-related code needs to change to accommodate changes elsewhere in the system, so it's taking a little bit more time than expected.

**Comment by Shillaker** [comment]
Hey @nayakajay I've updated the Python chaining API which is reflected in the [Python docs](https://github.com/lsds/Faasm/blob/master/docs/python.md). Functions are now chained by passing the function object directly, so there's no need for the decorators. Additionally the script itself no longer needs to be executable, it just needs to have a `faasm_main` function.

A simple example is shown in the docs, which also link to two further examples, including one that [shares a dictionary through state](https://github.com/lsds/Faasm/blob/master/func/python/dict_state.py). Faasm's shared state is built on creating pages of shared memory between functions, so the size of the state must always be specified. A function can query the size of a given state value using the `get_state_size` function, as is done in the example. If state changes size and will no longer fit in the originally provisioned memory, it must be written to a different key with sufficient space. This is also shown in the example when adding a third key/value entry to the dictionary changes the size of the serialised object.

When switching between Faasm versions it's good to delete the `machine-code` directory. So once you've updated you project I'd run something like:

```bash
# Clear machine code
rm -r machine-code

# Start up Faasm and wait for new machine code to be generated
docker-compose up

# Upload and invoke the demo chaining function
./bin/cli.sh
inv upload --py python dict_state
inv invoke --py python dict_state
```

Hope some of this is useful and let me know if there are any more issues.

**Comment by Shillaker** [comment]
Going to close these now as I've not heard anything but feel free to raise further issues if things don't work out.

**Comment by nayakajay** [comment]
Hi, sorry didn't get a chance to test it. I am sure this will work, but on a latest commit I am getting other issues. I have opened another issue. 
[https://github.com/lsds/Faasm/issues/234]

Thanks
