### ISSUE TITLE
Understanding Python Chaining API

### ISSUE THREAD

**Issue by nayakajay** [lsds/Faasm#213]
I am trying to understand the chaining API described over here:
https://github.com/lsds/Faasm/blob/master/docs/python.md#python-api

On using this, I see the error:
ModuleNotFoundError: No module named 'pyfaasm.code'

On looking at pyfaasm git, I don't see any code package

Is it a future possibility or am I missing something?

**Comment by nayakajay** [comment]
I have some clarifications related to python chaining, figured this is the right place to ask

There are 2 functions, which I want to execute one after the other, specifically, first functions output
is gonna be second function's input. 

There are 2 possibilities
1. As shown in the python README
```
f1 = chain_this_with_input(first, b'')
f2 = chain_this_with_input(second, b'')

await_call(f1)
await_call(f2)
```
In this case, are both f1 and f2 running in parallel? As in, if there are multiple workers (say 2 or more), will they run in parallel, and f2 won't wait for f1 to finish? Is this program racy?

2. Just another way of doing this.
```
f1 = chain_this_with_input(first, b'')
await_call(f1)

f2 = chain_this_with_input(second, b'')
await_call(f2)
```
This is definitely non-racy.

For analogy with python multiprocessing API, is
chain_this_with_input == Process.start()
await call                    == Process.join()

Just doubts.

**Comment by Shillaker** [comment]
Yes, you will have to guarantee that f1 has finished before you chain the call to f2, hence your second snippet is correct.

**Comment by nayakajay** [comment]
I was seeing some weird results on using snippet 1. I think I got it now.
Thanks for being so responsive.
