### ISSUE TITLE
Fail to run wasm demo in wasmer 

### ISSUE THREAD

**Issue by luckyfengyong** [lsds/Faasm#221]
@mfournial @Shillaker I like the idea to leverage wasm as runtime working with kantive to resolve the issues of performance and state. It is pretty straightforward to deploy faasm in k8s/knative and run a demo to understand the workflow. When I want to dig into the wavm of Faasm, I try to run the demo (hello) with another wasm runtime, wasmer, it failed with error message of "wasi_snapshot_preview1". 

I opened this issue just try to understand how to develop wasm program for faasm and how to test it standalone outside Faasm.

**Comment by Shillaker** [comment]
Hi @luckyfengyong, Faasm currently doesn't support wasmer, so the results of running WebAssembly from the Faasm repo with wasmer are undefined. Faasm uses [WAVM](https://github.com/WAVM/WAVM) under the hood, and has experimental support for [WAMR](https://github.com/bytecodealliance/wasm-micro-runtime). 

WebAssembly code in the Faasm repo is compiled with the WASI toolchain with a [few modifications](https://github.com/lsds/Faasm/blob/master/docs/toolchain.md), so simple examples that don't have any Faasm-specific code should still run ok (e.g. a C/C++ hello world that _doesn't_ include `faasm.h` or call any Faasm-specific functions). 

The issue you're seeing is related to the imports needed by the demo/hello function. Below is a subset of the WAST for this file, showing the `import`s:

```
(module
   ...
  (import "wasi_snapshot_preview1" "proc_exit" (func $__wasi_proc_exit (param i32)))
  (import "env" "__faasm_write_output" (func $__faasm_write_output (param i32 i32)))
  (import "env" "__faasm_get_idx" (func $__faasm_get_idx (result i32)))
  (import "wasi_snapshot_preview1" "args_sizes_get" (func $__wasi_args_sizes_get (param i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "args_get" (func $__wasi_args_get (param i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "fd_close" (func $__wasi_fd_close (param i32) (result i32)))
  ...
```

As you can see, the module expects to import WASI functions from a module named `wasi_snapshot_preview1` (which I think is the latest WASI standard). If this is not present then perhaps wasmer hasn't implemented this version of WASI. However, even if the WASI imports do resolve, it will still have trouble with the Faasm-related imports (e.g. `__faasm_write_output`), as these are only provided inside the Faasm runtime.

To run Faasm functions from the commandline, you can use the following:

```
# Open the CLI
./bin/cli.sh

# Compile, codegen, run
inv compile demo hello
inv codegen demo hello
inv run demo hello
```

If you need more detailed debugging and want to dig into the project, you'll need to look at setting up a [local development environment](https://github.com/lsds/Faasm/blob/master/docs/local_dev.md).

**Comment by luckyfengyong** [comment]
@Shillaker Thanks a lot. I will check the logic how `inv compile` works and follow the instruciton to develop wasm for Faasm. I also found the [issue ](https://github.com/bytecodealliance/wasi/issues/37) in wasi github regarding compatibility of snapshot migration.  But what you provided is more comprehensive. 

Thanks again.
