### ISSUE TITLE
Unable to upload using 'inv' command

### ISSUE THREAD

**Issue by nayakajay** [lsds/Faasm#234]
I am currently on the latest commit (master branch). 
the /bin/cli.sh suggests I am on **faasm CLI version : 0.1.3.**

I am having trouble while uploading functions i.e. with the command
**inv upload --py python dict_state**

In fact, I face the same issue with all files, not just python. Below command gives the same issue
inv upload demo hello

![Error_5_upload](https://user-images.githubusercontent.com/35248326/80366407-d94ef300-88a6-11ea-9e9c-862f8298d4aa.png)

Steps I did:
1. git clone Faasm
2. edit docker-compose to have PYTHON_CODEGEN=on
3. docker-compose up --scale worker=2
4. inv upload --py python dict_state

I am not sure what is wrong here. What I can see is in /bin/cli.sh environment python 3.6.9 is being used.

**Comment by Shillaker** [comment]
Hi @nayakajay . That seems strange, perhaps 0.1.3 is broken. Could you try updating to the latest master and running? This should use 0.1.4 which seems to work ok for me.

Thanks

**Comment by nayakajay** [comment]
Hi, I used **0.1.5.** which was the latest version, it works, was able to invoke both the functions.
I am closing this issue.
Thanks.
