### ISSUE TITLE
"EOFError: Ran out of input" on using shared memory

### ISSUE THREAD

**Issue by nayakajay** [lsds/faasm#250]
I am observing a strange behavior while using shared memory in python.

Below is the code snippet: **shm.py**
```
from pickle import loads, dumps
from random import randint
from pyfaasm.core import get_state, get_state_size, set_state, chain_this_with_input, await_call

KEY_A = "dict_func1"
KEY_B = "dict_func2"
KEY_C = "dict_func3"
KEY_D = "dict_func4"

#### Utilities for functions needed to read and write shared memory ###########

def get_dict_from_state(key):
    dict_size = get_state_size(key)
    pickled_dict = get_state(key, dict_size)
    return loads(pickled_dict)


def write_dict_to_state(key, dict_in):
    pickled_dict = dumps(dict_in)
    set_state(key, pickled_dict)

###############################################################################

def square_handler(input_bytes):
    input = randint(1,50)
    number = input * input
    response = {
        "from": "square",
        "statusCode": 200,
        "body": {"number":number}
    }
    write_dict_to_state(KEY_A, response)


def inc_handler(input_bytes):
    input = randint(1,50)
    number = input + 1
    response = {
        "from": "inc",
        "statusCode": 200,
        "body": {"number":number}
    }
    write_dict_to_state(KEY_B, response)


def half_handler(input_bytes):
    input = randint(1,50)
    number = input / 2
    response = {
        "from": "half",
        "statusCode": 200,
        "body": {"number":number}
    }
    write_dict_to_state(KEY_C, response)


def mod_handler(input_bytes):
    input = randint(1,50)
    number = input % 2
    response = {
        "from": "mod",
        "statusCode": 200,
        "body": {"number":number}
    }
    write_dict_to_state(KEY_D, response)

###############################################################################

# This is the main entrypoint
def faasm_main():

    # chained call, function 1
    square_id = chain_this_with_input(square_handler, b'')
    await_call(square_id)

    # chained call, function 2
    inc_id = chain_this_with_input(inc_handler, b'')
    await_call(inc_id)

    # chained call, function 3
    half_id = chain_this_with_input(half_handler, b'')
    await_call(half_id)

    # chained call, function 4
    mod_id = chain_this_with_input(mod_handler, b'')
    await_call(mod_id)

    # Load from state again
    for key in [KEY_A, KEY_B, KEY_C, KEY_D]:
    	print(get_dict_from_state(key))
```

I see inconsistent outputs for multiple runs for these as seen in screen shot. One is a success and next is a failure.
![Error_shm](https://user-images.githubusercontent.com/35248326/82019048-19ceaf00-96a4-11ea-94bf-f082609647f0.png)

Steps:
```
docker-compose up
inv upload --py python shm
inv invoke --py python shm
```

This works fine, sometimes, on continuous use of **invoke**, it fails [using below command]:
```
for i in {1..100}; do inv invoke --py python shm >> shm.out; done
```
faasm-cli: version 0.1.5

docker-compose.yml is changed a bit, particularly worker configuration
MAX_IN_FLIGHT_RATIO=10  # I don't think this should matter
MAX_WORKERS_PER_FUNCTION=10 # I have only 1 worker instance based on Steps

Is there a particular limit that each function has for shared memory that I am hitting?

**Comment by Shillaker** [comment]
Hi @nayakajay , I'll be able to look at this properly on Monday, but you may be missing a `push_state` after you call `set_state`. 

`get_state` and `set_state` operate on local shared memory, so changes made by `set_state` will be visible to functions executed on the same host (in this case, in the same container), but not to those on other hosts. To synchronise data between hosts you need to make sure you call `push_state` after you make local changes. `get_state` will implicitly call `pull_state` if the data is not already present (which will happen in this case).

So, if you add `push_state(key)` after `set_state(key, pickled_dict)` in `write_dict_to_state` it should work for you. Let me know if that helps and as I say, I can look again on Monday.

P.s. try to hold off from pulling from master for a couple of days. Version 0.2.0 contains some experimental changes to state that are a little unstable but I'm working on fixing them.

Cheers

**Comment by nayakajay** [comment]
I have not tried ```push_state(key)``` yet (will have it by EOD), but I am wondering if I really need it. For now, this is a local installation (should have mentioned it), which is running on a single host, and there is only **1 worker** container up. All the functions will execute in the same worker. I think I am missing something here.

Thanks

**Comment by nayakajay** [comment]
Hey, it took longer than expected:
So here is the modified write_dict_to_state() function:
```
def write_dict_to_state():
    pickled_dict = dumps(dict_in)
    set_state(key, pickled_dict)
    push_state(key)
``` 

The error still persists, as the screen shot above records it, but additionally, after the failure I observed above, when I retry again, I see a new error, which was not observed earlier.
![Error_shm_3](https://user-images.githubusercontent.com/35248326/82731568-880b1580-9d25-11ea-8cec-95dbd8c38d56.png)

This error is not something which I observed before, for some reason, next invocation is facing trouble because of earlier failure? [only after addition of ```push_state```]
