### ISSUE TITLE
Manifest Issue

### ISSUE THREAD

**Issue by mye-rutgers** [lsds/faasm#288]
Hello,

Recently when I tried to start a Faasm cluster by the ``docker-compose up --scale worker=2`` command, I had the following error: 

```console
ERROR: manifest for faasm/upload:0.4.3 not found: manifest unknown: manifest unknown
```

I would truly appreciate it if the issue could be resolved soon. 

Best Regards,
Mengmei

**Comment by Shillaker** [comment]
Hi Mengmei, I'll do another release today which should fix things up. Cheers!

**Comment by mye-rutgers** [comment]
@Shillaker Great! Thanks a lot!

**Comment by Shillaker** [comment]
Hi Mengmei, turns out a couple of containers hadn't built for release `0.4.3`. It should work now.

Let me know if you encounter any more issues.

Cheers

**Comment by Shillaker** [comment]
Hi Mengmei, yes that looks a bit odd, the worker is failing to start because it's getting a conflict between LLVM versions. You're right, the Docker quick-start shouldn't be affected by anything on your machine (other than your Docker installation).

Could you check whether the issue still persists with the current master version (0.4.4)? To make triple sure, could you delete all the faasm Docker images beforehand?

**Comment by mye-rutgers** [comment]
Hi @Shillaker, thanks a lot for the helpful instructions! I deleted all the faasm Docker images, and the current master version works perfectly fine now :) 

Just for your reference, my Docker version is 19.03.12, and my docker-compose version is 1.26.2.

**Comment by Shillaker** [comment]
Ok great! I'll close this issue now but feel free to raise others if you have any more issues.

Cheers

**Comment by mengmeiye** [comment]
Hello again!

Previously I worked on `v0.4.4`. I could run the given examples but failed to recompile them. Therefore, I switched to the current `v0.4.10` but encountered the following issues:
```console
worker_2       | /faasm/build/bin/pool_runner: error while loading shared libraries: libpistache.so.0: cannot open shared object file: No such file or directory
upload_1       | /faasm/build/bin/upload: error while loading shared libraries: libpistache.so.0: cannot open shared object file: No such file or directory
worker_1       | Setting up namespaces
worker_1       | Network namespace support is off
faasm_worker_2 exited with code 127
worker_1       | /faasm/build/bin/pool_runner: error while loading shared libraries: libpistache.so.0: cannot open shared object file: No such file or directory
faasm_upload_1 exited with code 127
faasm_worker_1 exited with code 127
nginx_1        | 2020/10/15 14:55:49 [emerg] 1#1: host not found in upstream "worker" in /etc/nginx/nginx.conf:10
nginx_1        | nginx: [emerg] host not found in upstream "worker" in /etc/nginx/nginx.conf:10
faasm_nginx_1 exited with code 1
```

Then, I tried to use `v0.4.9`. Building the cluster worked fine, but when I ran the CLI, I saw the following error message:
```
Unable to find image 'faasm/toolchain:0.4.9' locally
docker: Error response from daemon: manifest for faasm/toolchain:0.4.9 not found: manifest unknown: manifest unknown.
```

Would you mind providing some help with how to add the `toolchain:0.4.9` into the CLI? I would truly appreciate it!

Best Regards,
Mengmei

**Comment by mye-rutgers** [comment]
Hello again!

Previously I worked on `v0.4.4`. I could run the given examples but failed to recompile them. Therefore, I switched to the current `v0.4.10` but encountered the following issues:
```console
worker_2       | /faasm/build/bin/pool_runner: error while loading shared libraries: libpistache.so.0: cannot open shared object file: No such file or directory
upload_1       | /faasm/build/bin/upload: error while loading shared libraries: libpistache.so.0: cannot open shared object file: No such file or directory
worker_1       | Setting up namespaces
worker_1       | Network namespace support is off
faasm_worker_2 exited with code 127
worker_1       | /faasm/build/bin/pool_runner: error while loading shared libraries: libpistache.so.0: cannot open shared object file: No such file or directory
faasm_upload_1 exited with code 127
faasm_worker_1 exited with code 127
nginx_1        | 2020/10/15 14:55:49 [emerg] 1#1: host not found in upstream "worker" in /etc/nginx/nginx.conf:10
nginx_1        | nginx: [emerg] host not found in upstream "worker" in /etc/nginx/nginx.conf:10
faasm_nginx_1 exited with code 1
```

Then, I tried to use `v0.4.9`. Building the cluster worked fine, but when I ran the CLI, I saw the following error message:
```
Unable to find image 'faasm/toolchain:0.4.9' locally
docker: Error response from daemon: manifest for faasm/toolchain:0.4.9 not found: manifest unknown: manifest unknown.
```

Would you mind providing some help with how to add the `toolchain:0.4.9` into the CLI? I would truly appreciate it!

Best Regards,
Mengmei
