### ISSUE TITLE
Unclear that project assumes location at /usr/local/code/faasm

### ISSUE THREAD

**Issue by bushidocodes** [lsds/Faasm#99]
Hi! Very interesting work here! I'm trying to run your `docker-compose` based quickstart and it seems that the upload service dies nearly immediately. Here are the relevant logs.

```
upload_1       | Generating object file for Python
upload_1       | [2019-11-18 17:10:47.718] [console] [info] Running codegen for function python/py_func
upload_1       | [2019-11-18 17:10:47.719] [console] [error] Invalid function: python/py_func
upload_1       | [2019-11-18 17:10:47.719] [console] [info] Generating machine code for python/py_func
upload_1       | terminate called after throwing an instance of 'std::runtime_error'
upload_1       |   what():  No fileserver URL set in fileserver mode
upload_1       | /entrypoint.sh: line 16:     7 Aborted                 ./bin/codegen_func python py_func
```

Glancing at the source, I looks like this might be coming from `codegen_func.cpp`. Not sure if this helps, but it looks like codegenForFunction is getting run even if the msg contains an invalid function.

```cpp
void codegenForFunc(const std::string &user, const std::string &func) {
    const std::shared_ptr<spdlog::logger> logger = util::getLogger();

    message::Message msg = util::messageFactory(user, func);
    if (!util::isValidFunction(msg)) {
        logger->error("Invalid function: {}/{}", user, func);
    }

    logger->info("Generating machine code for {}/{}", user, func);
    storage::FileLoader &loader = storage::getFileLoader();
    loader.codegenForFunction(msg);
}
```

**Comment by bushidocodes** [comment]
After spending a bit more time with this, it seems that everything sort of boils down to there being an implicit assumption that I git clone your project into `/usr/local/code/faasm/`. Perhaps I missed this somewhere in the documentation, but it might be worth making trying to make this a bit more clear in the docs.

**Comment by Shillaker** [comment]
Hello @bushidocodes, thanks for the interest and sorry for the slow response. This is a bit of a relic that needs tidying up so I'll see what I can do. Thanks for raising
